services:
  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_ERLANG_COOKIE=a_very_long_secret_cookie_for_rabbitmq_4_0
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  postgres:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg18
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_applicator
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d job_applicator']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
