receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  file_log:
    include: ['${env:LOGS_DIR}/*/*-json.log']

processors:
  batch:

exporters:
  otlphttp/newrelic:
    endpoint: ${env:NEWRELIC_OTLP_ENDPOINT}
    headers:
      api-key: ${env:NEWRELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/newrelic]
    logs:
      receivers: [otlp, file_log]
      processors: [batch]
      exporters: [otlphttp/newrelic]
