services:
  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_ERLANG_COOKIE=a_very_long_secret_cookie_for_rabbitmq_4_0
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    profiles:
      - infrastructure
  postgres:
    image: pgvector/pgvector:pg18
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_applicator
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d job_applicator']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    profiles:
      - infrastructure
  ollama:
    profiles:
      - ai
    image: lojzatran/job-applicator-ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/tags']
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
  api:
    profiles:
      - app
    image: lojzatran/job-applicator-api:latest
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      OLLAMA_JOB_EVALUATOR_MODEL: gemma3:4b-cloud
      OLLAMA_BASE_URL: https://ollama.com
      COVER_LETTER_GENERATOR_MODEL: gemma3:4b-cloud
      CV_PARSER_MODEL: gemma3:4b-cloud
      CRITIQUE_MODEL: gemma3:4b-cloud
      COHERE_API_KEY: ${COHERE_API_KEY}
      COHERE_EMBEDDING_MODEL: ${COHERE_EMBEDDING_MODEL}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY}
      LANGSMITH_PROJECT: ${LANGSMITH_PROJECT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_TRACING: ${LANGSMITH_TRACING}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_applicator
      STORAGE_DIR: /app/uploads
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
      - ../logs:/app/logs

  website:
    profiles:
      - app
    image: lojzatran/job-applicator-website:latest
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://rabbitmq:5672
      POSTGRES_HOST: postgres
      POSTGRES_PORT: '5432'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_applicator
      STORAGE_DIR: /app/uploads
      LOGS_DIR: /app/logs
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
      - ../logs:/app/logs

  db-reset:
    image: lojzatran/job-applicator-db-reset:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_applicator
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tools-reset

  db-migrate:
    image: lojzatran/job-applicator-db-migrate:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_applicator
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tools-migrate

  otel-collector:
    profiles:
      - observability
    image: otel/opentelemetry-collector-contrib
    user: '0:0'
    environment:
      - LOGS_DIR=/var/lib/docker/containers
      - NEWRELIC_LICENSE_KEY=${NEWRELIC_LICENSE_KEY}
      - NEWRELIC_OTLP_ENDPOINT=${NEWRELIC_OTLP_ENDPOINT}
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./otel-collector-config.base.yaml:/etc/otelcol-contrib/config.yaml
    command:
      - --config=/etc/otelcol-contrib/config.yaml
    ports:
      - 13133:13133 # health_check extension
      - 4318:4318 # OTLP http receiver

volumes:
  postgres_data:
  ollama_data:
  uploads:
