FROM node:22-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production

COPY tsconfig.base.json ./tsconfig.base.json
COPY libs/shared/package.docker.json ./libs/shared/package.json
COPY libs/shared/src ./libs/shared/src
COPY libs/migrations/package.json ./package.json

RUN npm install --no-audit --no-fund

COPY libs/migrations/src ./libs/migrations/src

RUN chown -R node:node /app
USER node

CMD ["npm", "run", "db:reset"]
