import './global.css';
import { ThemePreferenceProvider } from './context/theme-preference-context';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemePreferenceProvider>{children}</ThemePreferenceProvider>
      </body>
    </html>
  );
}
